[package]
name = "libktx-rs-sys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "build/build.rs"

[features]
# Link libstdc++. Required on Linux if using `CXX=g++`.
# Alternatively, for full-LLVM builds (recommended):
# 1. Set `CC=clang`, `CXX=clang++` to replace GCC with Clang
# 2. Set `CXXSTDLIB=stdc++` to use clang's libc++
# 3. Copy https://github.com/bevyengine/bevy/blob/main/.cargo/config_fast_builds to use clang instead of gcc as a linker
"link-libstdc++" = []

[dependencies]

[build-dependencies]
cc = { version = "^1.0", features = ["parallel"] }
bindgen = "^0.58"
